name = "matomesaito"
main = "src/index.ts"
compatibility_date = "2026-06-14"
account_id = "26c7e8e9cacd87df91ea5ae48d205794"

[triggers]
crons = ["17 18 * * *"]

[[kv_namespaces]]
binding = "BLOCKLIST_KV"
id = "4b6eb4392fd64968a00ab1c45209a975"

[vars]
USER_AGENT = "matomesaito-bot/0.1 (+https://github.com/yourname/matomesaito)"
